=== diogogsilva/dweb2019/tp4/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pr (metadata, workteam, abstract, deliverables?) >
<!ELEMENT metadata (keyname, title, subtitle?, supervisor, bdate, edate) >
<!ELEMENT keyname (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT bdate (#PCDATA) >
<!ELEMENT edate (#PCDATA) >

<!ELEMENT supervisor (#PCDATA)>
<!ATTLIST supervisor
                homepage CDATA #IMPLIED>

<!ELEMENT workteam (member)+ >
<!ELEMENT member (identifier, name, email, git?) >
<!ELEMENT identifier (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT git (#PCDATA) >

<!ELEMENT abstract (p)+ >
<!ELEMENT p (#PCDATA|b|i|u|xref)* >
<!ELEMENT b (#PCDATA|i|u|xref)* >
<!ELEMENT i (#PCDATA|u|b|xref)* >
<!ELEMENT u (#PCDATA|i|b|xref)* >
<!ELEMENT xref (#PCDATA) >
<!ATTLIST xref 
            url CDATA #REQUIRED>
            
<!ELEMENT deliverables (deliverable)+ >
<!ELEMENT deliverable (#PCDATA) >
<!ATTLIST deliverable
            path CDATA #REQUIRED >

=== diogogsilva/dweb2019/tp6/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "PR.dtd">
<pr>
    <metadata>
        <keyname>TP4_MEI2019_DAW</keyname>
        <title>Trabalho Prático 6</title>
        <subtitle>Desenvolvimento de Aplicações Web</subtitle>
        <supervisor homepage="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
        <bdate>21 de Outubro 2019</bdate>
        <edate>28 de Outubro 2019</edate>
    </metadata>
    <workteam>
        <member>
            <identifier>PG41070</identifier>
            <name>Diogo Filipe Gigante da Silva</name>
            <email>pg41070@alunos.uminho.pt</email>
            <git>https://github.com/diogogsilva/dweb2019</git>
        </member>
    </workteam>
    <abstract>
        <p>Trabalho Prático Número 6.<b>Desenvolvimento de Aplicações Web</b></p>
        <p>-> App para gerir lista de arquivos sonoros</p>
        <p>-> pr.html</p>
        <p>-> pr.xml</p>
        <p><i>By:</i><u><xref url="https://github.com/diogogsilva/dweb2019">Diogo Silva</xref></u></p>
    </abstract>
    <deliverables>
        <deliverable path="http://www4.di.uminho.pt/~jcr/XML/didac/xmldocs/PR.htm">Project Record</deliverable>
        <deliverable path="http://www4.di.uminho.pt/~jcr/XML/didac/xmldocs/arq-son-EVO.xml">Arq-Son-Evo.xml</deliverable>
    </deliverables>
</pr>

=== diogogsilva/dweb2019/tp9/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "PR.dtd">
<pr>
    <metadata>
        <keyname>TP9_MEI2019_DAW</keyname>
        <title>Trabalho Prático 9</title>
        <subtitle>Desenvolvimento de Aplicações Web</subtitle>
        <supervisor homepage="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
        <bdate>11 de Novembro 2019</bdate>
        <edate>18 de Novembro 2019</edate>
    </metadata>
    <workteam>
        <member>
            <identifier>PG41070</identifier>
            <name>Diogo Filipe Gigante da Silva</name>
            <email>pg41070@alunos.uminho.pt</email>
            <git>https://github.com/diogogsilva/dweb2019</git>
        </member>
    </workteam>
    <abstract>
        <p>Trabalho Prático Número 9.<b>Desenvolvimento de Aplicações Web</b></p>
        <p>-> App em Node para automatizar o comando MongoImport</p>
        <p><i>By:</i><u><xref url="https://github.com/diogogsilva/dweb2019">Diogo Silva</xref></u></p>
    </abstract>
</pr>

=== diogogsilva/dweb2019/PL10/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "PR.dtd">
<pr>
    <metadata>
        <keyname>TP10_MEI2019_DAW</keyname>
        <title>Trabalho Prático 10</title>
        <subtitle>Desenvolvimento de Aplicações Web</subtitle>
        <supervisor homepage="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
        <bdate>19 de Novembro 2019</bdate>
        <edate>26 de Novembro 2019</edate>
    </metadata>
    <workteam>
        <member>
            <identifier>PG41070</identifier>
            <name>Diogo Filipe Gigante da Silva</name>
            <email>pg41070@alunos.uminho.pt</email>
            <git>https://github.com/diogogsilva/dweb2019</git>
        </member>
    </workteam>
    <abstract>
        <p>Trabalho Prático Número 10.<b>Desenvolvimento de Aplicações Web</b></p>
        <p>-> App para Gerir Ficheiros (Download e Upload)</p>
        <p>-> pr.html</p>
        <p>-> pr.xml</p>
        <p><i>By:</i><u><xref url="https://github.com/diogogsilva/dweb2019">Diogo Silva</xref></u></p>
    </abstract>
    <deliverables>
        <deliverable path="http://www4.di.uminho.pt/~jcr/XML/didac/xmldocs/PR.htm">Project Record</deliverable>
    </deliverables>
</pr>

=== diogogsilva/dweb2019/tp3/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "PR.dtd">
<pr>
    <metadata>
        <keyname>TP3_MEI2019_DAW</keyname>
        <title>Trabalho Prático 3</title>
        <subtitle>Desenvolvimento de Aplicações Web</subtitle>
        <supervisor homepage="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
        <bdate>1 de Outubro 2019</bdate>
        <edate>8 de Outubro 2019</edate>
    </metadata>
    <workteam>
        <member>
            <identifier>PG41070</identifier>
            <name>Diogo Filipe Gigante da Silva</name>
            <email>pg41070@alunos.uminho.pt</email>
            <git>https://github.com/diogogsilva/dweb2019</git>
        </member>
    </workteam>
    <abstract>
        <p>Trabalho Prático Número 3.<b>Desenvolvimento de Aplicações Web</b></p>
        <p>-> PR.xml</p>
        <p>-> PR.xsl</p>
        <p>-> PR.html</p>
        <p>-> arq.xsl</p>
        <p>-> website arq</p>
        <p><i>By:</i><u><xref url="https://github.com/diogogsilva/dweb2019">Diogo Silva</xref></u></p>
    </abstract>
    <deliverables>
        <deliverable path="http://www4.di.uminho.pt/~jcr/XML/didac/xmldocs/PR.htm">Project Record</deliverable>
        <deliverable path="http://www4.di.uminho.pt/~jcr/XML/didac/xmldocs/arq.xml">Arqueossitios</deliverable>
    </deliverables>
</pr>

=== diogogsilva/dweb2019/TESTE/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "PR.dtd">
<pr>
    <metadata>
        <keyname>DWEB2019::Teste::PG41070</keyname>
        <title>Teste PG41070</title>
        <subtitle>Desenvolvimento de Aplicações Web</subtitle>
        <supervisor homepage="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
        <bdate>16 de Janeiro 2020</bdate>
        <edate>16 de Janeiro 2020</edate>
    </metadata>
    <workteam>
        <member>
            <identifier>PG41070</identifier>
            <name>Diogo Filipe Gigante da Silva</name>
            <email>pg41070@alunos.uminho.pt</email>
            <git>https://github.com/diogogsilva/dweb2019</git>
        </member>
    </workteam>
    <abstract>
        <p>Teste de Avaliação.<b>Desenvolvimento de Aplicações Web</b></p>
        <p>-> arquivo-musica-digital.xml</p>
        <p>-> arquivo.json</p>
        <p>-> perguntasQueries.txt</p>
        <p>(Parte 1) Diretoria: arquivos</p>
        <p>   Passo 1 - Para importar a base dados para o Mongo, dentro da pasta Teste:</p>
        <p>   Passo 2 - mongoimport -d arquivos -c arquivos arquivo.json --jsonArray</p>
        <p>   Passo 3 - Para inicar o servidor, dentro da pasta arquivos</p>
        <p>   Passo 4 - npm install</p>
        <p>   Passo 5 - npm start</p>
        <p>(Parte 2) Diretoria: entidades</p>
        <p>Passo 1 - Para inicar o servidor, dentro da pasta entidades</p>
        <p>Passo 2 - npm install</p>
        <p>Passo 3 - npm start</p>
        <p>-> pr.xml</p>
        <p>-> pr.html</p>
        <p><i>By:</i><u><xref url="https://github.com/diogogsilva/dweb2019">Diogo Silva</xref></u></p>
    </abstract>
    <deliverables>
        <deliverable path="http://www4.di.uminho.pt/~jcr/XML/didac/xmldocs/PR.htm">Project Record</deliverable>
        <deliverable path="http://www4.di.uminho.pt/~jcr/AULAS/didac/RepFichas/site/fichas/daw2020-e1.html">Enunciado</deliverable>
    </deliverables>
</pr>
